// <auto-generated />
using CoursesWorkshop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoursesWorkshop.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220211162905_InstructorUpdate")]
    partial class InstructorUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoursesWorkshop.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "Museum",
                            DepartmentCode = "BIOC",
                            InstructorId = 1,
                            Name = "Biochemistry",
                            RoomNumber = 1234
                        },
                        new
                        {
                            Id = 2,
                            Building = "Empire State Building",
                            DepartmentCode = "PSYC",
                            InstructorId = 2,
                            Name = "Psychology",
                            RoomNumber = 205
                        },
                        new
                        {
                            Id = 3,
                            Building = "Sears Tower",
                            DepartmentCode = "MATH",
                            InstructorId = 3,
                            Name = "Calculus",
                            RoomNumber = 8745
                        });
                });

            modelBuilder.Entity("CoursesWorkshop.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "BIOC",
                            Email = "blah@blah.gov",
                            FirstName = "Carlos",
                            LastName = "Lopez"
                        },
                        new
                        {
                            Id = 2,
                            Department = "PSYC",
                            Email = "gav@blah.gov",
                            FirstName = "Gavin",
                            LastName = "Hensley"
                        },
                        new
                        {
                            Id = 3,
                            Department = "MATH",
                            Email = "great@blah.gov",
                            FirstName = "Davis",
                            LastName = "Murphy"
                        });
                });

            modelBuilder.Entity("CoursesWorkshop.Models.Course", b =>
                {
                    b.HasOne("CoursesWorkshop.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CoursesWorkshop.Models.Instructor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
