// <auto-generated />
using CoursesWorkshop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoursesWorkshop.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220210161704_AddedSeedData")]
    partial class AddedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoursesWorkshop.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "Museum",
                            DepartmentCode = "BIOC",
                            Instructor = "Carlos Lopez",
                            Name = "Biochemistry",
                            RoomNumber = 1234
                        },
                        new
                        {
                            Id = 2,
                            Building = "Empire State Building",
                            DepartmentCode = "PSYC",
                            Instructor = "Gavin Hensley",
                            Name = "Psychology",
                            RoomNumber = 205
                        },
                        new
                        {
                            Id = 3,
                            Building = "Sears Tower",
                            DepartmentCode = "MATH",
                            Instructor = "Davis Murphy",
                            Name = "Calculus",
                            RoomNumber = 8745
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
